// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Zurich",
                            Country = "Switzerland",
                            Rating = 5,
                            Review = "Great"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Osaka",
                            Country = "Japan",
                            Rating = 1,
                            Review = "Excellent"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Stockholm",
                            Country = "Sweden",
                            Rating = 10,
                            Review = "Meh"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Mexico City",
                            Country = "Mexico",
                            Rating = 10,
                            Review = "Awesome"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Oxford",
                            Country = "England",
                            Rating = 4,
                            Review = "Brilliant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
